name: "Code Enhancement / Refactor"
description: Suggest improvements or refactoring for TS-Bhai codebase
labels: [enhancement, refactor]

body:
  - type: markdown
    attributes:
      value: |
        Got an idea for improving the codebase of **TS-Bhai**?  
        Please review the TS-Bhai Language Specification before reporting:  
        https://github.com/journeycodesayush/ts-bhai/blob/main/docs/language.md  
        Whether it's refactoring a function, improving readability, optimizing performance,
        or enhancing frontend/playground code, share your thoughts below.
        **Note:** TS-Bhai is a **playground / demo**.
        Some language features may be limited or behave differently than the full
        implementation.
        For full BhaiLang behavior, check **JavaBhaiLang** locally:  
        https://github.com/journeycodesayush/javabhailang
        Also, refer to the TS-Bhai Language Specification for expected behavior.

  - type: textarea
    id: enhancement-summary
    attributes:
      label: Enhancement Summary
      placeholder: "Refactor the lexer to support more flexible token patterns"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Why and How?
      placeholder: |
        Why is this enhancement needed?  
        What changes do you suggest, and how should they improve TS-Bhai?  
        Include notes about whether this affects the interpreter, parser, frontend, or all of them.
    validations:
      required: true

  - type: checkboxes
    id: affected_parts
    attributes:
      label: Which part of TS-Bhai does this enhancement touch?
      options:
        - label: Lexer (token definitions)
        - label: Parser (grammar / AST)
        - label: Interpreter (runtime behavior)
        - label: Built-in functions / keywords
        - label: Frontend Playground / UI
        - label: Examples / documentation
        - label: Other
